package com.wijeratnefurniture.ecomfurniture.entity;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document // -> MongoDB
//@Entity() // ->mysql
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Getter
@Setter
public class Supplier {
    @Id //@Id annotation to pass data to MongoDB  //id is autogenerated
    private String id;  //we use id just after @Id annotation to say that this is the primary key

    private String firstName; 
    private String lastName; 
    private String companyName; 
    private String address; 
    private String NIC;
    private String email;      
    private String password;
    private String photo; 
    private int mobilePhonenumber;
    private int LandLinePhonenumber;
    private String description;
    private String supplyItemsList; 

}
