package com.wijeratnefurniture.ecomfurniture.entity;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document // -> MongoDB
//@Entity() // ->mysql
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Getter
@Setter
public class User {
    

    @Id //@Id annotation to pass data to MongoDB  //id is autogenerated
    private String id;  //we use id just after @Id annotation to say that this is the primary key

    private String firstName; 
    private String lastName; 
    private String address; 
    private String gender; 
    private String NIC;
    private String role;
    private String userName;      
    private String password;
// image to be added
    private float age;
    private String DOB;

}
